# Generated by Django 5.2.5 on 2025-08-23 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogwebapp", "0004_alter_blog_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 23, 16, 4, 39, 168000)
            ),
        ),
    ]
