# Generated by Django 5.2.5 on 2025-08-23 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogwebapp", "0005_alter_blog_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 23, 17, 6, 0, 755019)
            ),
        ),
    ]
