# Generated by Django 5.2.5 on 2025-08-23 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogwebapp", "0006_alter_blog_date_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="blogpage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("Author", models.CharField(max_length=100)),
                (
                    "date_time",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 8, 23, 21, 52, 47, 273848)
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name="users",
            new_name="nusers",
        ),
        migrations.DeleteModel(
            name="BLOG",
        ),
    ]
