# Generated by Django 5.2.5 on 2025-08-23 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogwebapp", "0007_blogpage_rename_users_nusers_delete_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 23, 21, 54, 57, 512427)
            ),
        ),
        migrations.AlterField(
            model_name="nusers",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
