# Generated by Django 5.2.5 on 2025-08-23 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogwebapp", "0008_alter_blogpage_date_time_alter_nusers_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 23, 22, 27, 11, 486834)
            ),
        ),
    ]
