# Generated by Django 5.2.5 on 2025-08-24 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogwebapp", "0009_alter_blogpage_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 24, 10, 19, 2, 12429)
            ),
        ),
        migrations.AlterField(
            model_name="nusers",
            name="email",
            field=models.EmailField(max_length=254, null=None, unique=True),
        ),
    ]
