# Generated by Django 5.2.5 on 2025-08-24 04:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogwebapp", "0010_alter_blogpage_date_time_alter_nusers_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 24, 10, 20, 20, 186688)
            ),
        ),
        migrations.AlterField(
            model_name="nusers",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="nusers",
            name="password",
            field=models.CharField(),
        ),
    ]
