# Generated by Django 5.2.5 on 2025-08-24 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogwebapp", "0011_alter_blogpage_date_time_alter_nusers_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 24, 10, 27, 3, 24277)
            ),
        ),
    ]
