# Generated by Django 5.2.5 on 2025-08-24 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogwebapp", "0012_alter_blogpage_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 24, 15, 21, 38, 756571)
            ),
        ),
    ]
