# Generated by Django 5.2.5 on 2025-08-31 04:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogwebapp", "0013_alter_blogpage_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="date_time",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 8, 31, 9, 32, 25, 74898)
            ),
        ),
    ]
